<a href="https://colab.research.google.com/github/lamiaehana/bertelsmann-technology-scholarship-program/blob/master/Torch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
% matplotlib inline
% config InlineBackend.figure_format = 'retina'

In [0]:
import torch

In [0]:
import torchvision 

In [22]:
print(torch.cuda.is_available())

False


#Torch Tensors

In [23]:
#this is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [24]:
#this is a 2-D Tensor
b = torch.tensor([[2,1,4], [3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [25]:
#the size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [28]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [0]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do 
#c = torch.tensor([2,2,1], dtype = torch.float)

In [0]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [36]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [37]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [38]:
print(c.mean())

tensor(2.5833)


In [39]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [40]:
print(c.std())

tensor(1.5050)


In [41]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [46]:
#Reshape b
#Note : if one of the dimension is -1, its size can be inferred
print(b)
print(b.view(-1,1))

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])
tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])


In [49]:
print(b.view(12))

tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])


In [50]:
print(b.view(-1,4))

tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])


In [51]:
print(b.view(3,4))

tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])


In [52]:
#Assign b a new shape
b = b.view(1,-1)
print(b)

tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])


In [53]:
print(b.shape)

torch.Size([1, 12])


In [54]:
#We can even reshape 30 tensors
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles, rows, columns)
three_dim = torch.randn(2,3,4)
print(three_dim)

tensor([[[ 0.9353,  0.6546,  1.2782,  1.0183],
         [-0.2833,  1.2126, -1.9375,  2.3675],
         [-0.1957,  0.5938, -0.4529, -0.3103]],

        [[ 0.3728, -0.4728,  0.0225, -0.1717],
         [-1.6108, -1.1699, -0.2912,  1.0971],
         [ 0.9387, -0.7719,  0.6574, -0.9410]]])


In [55]:
print(three_dim.view(2,12)) #Reshape to 2 rows, 12 columns

tensor([[ 0.9353,  0.6546,  1.2782,  1.0183, -0.2833,  1.2126, -1.9375,  2.3675,
         -0.1957,  0.5938, -0.4529, -0.3103],
        [ 0.3728, -0.4728,  0.0225, -0.1717, -1.6108, -1.1699, -0.2912,  1.0971,
          0.9387, -0.7719,  0.6574, -0.9410]])


In [56]:
print(three_dim.view(2,-1))

tensor([[ 0.9353,  0.6546,  1.2782,  1.0183, -0.2833,  1.2126, -1.9375,  2.3675,
         -0.1957,  0.5938, -0.4529, -0.3103],
        [ 0.3728, -0.4728,  0.0225, -0.1717, -1.6108, -1.1699, -0.2912,  1.0971,
          0.9387, -0.7719,  0.6574, -0.9410]])


In [57]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.8291, 0.9680, 0.8791, 0.8128],
        [0.2512, 0.5571, 0.8138, 0.9101],
        [0.6951, 0.7054, 0.6602, 0.0623],
        [0.9638, 0.4240, 0.8076, 0.8647]])


In [59]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 0.3000, -1.6362,  2.6602,  0.8817],
        [ 1.3888, -0.2119,  0.2873,  0.5952],
        [-0.7275, -0.1182,  1.4321, -0.4597],
        [ 1.5139,  1.6220,  0.1999, -0.9352]])
torch.float32


In [64]:
#Create an array of 5 random integers from values between  6 and 9 (exclusive of 10)
in_array = torch.randint(6,10,(5,))
print(in_array)
print(in_array.dtype)

tensor([9, 6, 9, 6, 8])
torch.int64


In [65]:
#Create a 2-D (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exclusive of 10)
in_array2 = torch.randint(6,10,(3,3))
print(in_array2)

tensor([[6, 8, 8],
        [9, 6, 6],
        [6, 9, 8]])


In [66]:
#Get the number of elements in in_array
print(torch.numel(in_array))

5


In [67]:
print(torch.numel(in_array2))

9


In [68]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3,3, dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [69]:
#Construct a 3x3 matrix og ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [70]:
r2_like = torch.randn_like(r2,dtype = torch.double) #Convert the data type of the tensor
print(r2_like)

tensor([[-6.1040e-01, -1.1725e+00,  6.5268e-01,  1.8548e+00],
        [ 9.7515e-01,  2.4428e-03, -1.9105e-01, -1.0682e+00],
        [-8.0176e-01,  5.6065e-01,  2.6304e+00, -9.2666e-01],
        [ 6.6057e-02,  5.2973e-01,  5.4346e-01,  1.6447e-01]],
       dtype=torch.float64)


In [71]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 1.1291, -0.6682,  3.5393,  1.6945],
        [ 1.6400,  0.3451,  1.1011,  1.5053],
        [-0.0324,  0.5872,  2.0922, -0.3973],
        [ 2.4777,  2.0460,  1.0074, -0.0705]])


In [72]:
#In-place addition(change the value of r2)
r2.add_(r)
print(r2)

tensor([[ 1.1291, -0.6682,  3.5393,  1.6945],
        [ 1.6400,  0.3451,  1.1011,  1.5053],
        [-0.0324,  0.5872,  2.0922, -0.3973],
        [ 2.4777,  2.0460,  1.0074, -0.0705]])
